//
//  LargeView.swift
//  NavigationBarStylingInSwiftUI
//
//  Created by Ramill Ibragimov on 09.05.2021.
//

import Foundation

class LargeView {
    
    static let text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nisi ex, pulvinar ac lacus ac, elementum laoreet urna. Suspendisse id pretium nibh, eget fermentum sem. Etiam nec ullamcorper tellus, sed euismod neque. Pellentesque laoreet leo eget augue egestas volutpat. Etiam malesuada sem nunc, a condimentum enim ornare in. Fusce porttitor ultricies urna eget tempus. Fusce ultrices, ex in interdum molestie, massa nibh lacinia quam, at lobortis metus lacus sit amet enim. Nullam quis vulputate ante. Suspendisse venenatis commodo faucibus. Sed molestie nisi non lorem pharetra, ut laoreet quam tristique. Nulla non lobortis nisl. Nulla rutrum, massa vel gravida euismod, eros tellus placerat nisl, quis lobortis neque neque eu elit. Nunc neque massa, tempor ut sapien nec, congue vulputate nibh. Duis id dignissim arcu. Aliquam ac mollis eros. Proin consectetur, dolor et ultricies facilisis, nisl nulla suscipit sem, at viverra justo elit at tellus. Quisque vulputate non ex sed rutrum. Praesent eget dui vel nunc laoreet fermentum. Nam tincidunt lectus neque, quis viverra arcu consectetur eget. Nullam rutrum velit dolor, non finibus elit feugiat euismod. Mauris gravida metus leo, scelerisque ultrices metus luctus imperdiet. Ut tristique metus a purus vehicula luctus. Nam condimentum scelerisque nisi eu pellentesque. Fusce sodales volutpat ligula a blandit. Praesent feugiat enim ac aliquet varius. Maecenas in erat ut dui condimentum porta. Praesent dignissim quam vitae dui porttitor, a auctor lectus consectetur. Vestibulum vitae euismod elit. Aliquam at nibh quis diam rhoncus dignissim. Ut ut nisl a libero eleifend bibendum ac id ante. Donec quis mauris velit. Proin nibh augue, lobortis sit amet euismod id, sagittis ut est. Donec mattis finibus auctor. Aliquam varius libero ut venenatis facilisis. Praesent vel leo id quam egestas viverra. Fusce maximus laoreet mattis. Aenean a lacus egestas, accumsan lorem et, fermentum lorem. Morbi eget quam tortor. Sed vehicula est et nunc rutrum tincidunt a eu augue. Nulla ornare id magna at tristique. Aenean purus urna, consequat in magna in, posuere feugiat massa. Vivamus neque nulla, commodo ac lectus eu, maximus rhoncus orci. Maecenas imperdiet ante mi, auctor mattis enim tempus pretium. Sed sit amet efficitur elit. Vestibulum leo dui, porttitor a venenatis et, maximus sit amet purus. Proin a pulvinar justo. Etiam eu tristique tellus. Phasellus eget nisl et sapien interdum mattis. Vivamus aliquet vel tellus nec ultrices. Pellentesque gravida turpis quis orci posuere commodo. Etiam facilisis enim vitae eleifend interdum. In lobortis risus metus, at pellentesque nisi scelerisque non. Ut sollicitudin, nisi ut aliquam efficitur, urna eros imperdiet metus, vel blandit metus mauris vitae erat. Suspendisse auctor tempor vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent ornare convallis nisl, et fermentum nunc. Nullam eget cursus arcu."
}
